---
data_dir: example_data
model_dir: same
overwrite: True
random_state: 42

data_prefix: [cta-brain]
label_prefix: [brain-mask-mc]
mask_prefix: [brain-mask-mc]
mask_dilate: [100, 100, 100]
filter_zero: 0.

input_function: PatchInputFn3D
data_plane: ax
train_dims: [80, 80, 80]
train_patch_overlap: [2, 2, 2]
infer_dims: [256, 256, 256]
infer_patch_overlap: [1.5, 1.5, 1.5]
augment_train_data: True
label_interp: 0

norm_data: False
norm_labels: False
norm_mode: zscore

model_name: Unet3dBneck
base_filters: 32
output_filters: 1
layer_layout: [3, 4, 4]
final_layer: sigmoid
kernel_size: [3, 3, 3]
data_format: channels_last
activation: leaky_relu
mixed_precision: False
dist_strat: none

shuffle_size: 500
batch_size: 6
samples_per_epoch: 6000
num_threads: 4
train_fract: 1.0
learning_rate: [0.001, 12, 0.5]
learning_rate_decay: simple_step
optimizer: adam
loss: combo_loss3d
metrics: [bce]
num_epochs: 20
dropout_rate: 0.4
